Feature viewer functionality
HellInsider/Shopping-Mall-Maps pull request #15
Opened 2021-03-29 20:29 UTC by HellInsider

2021-03-29 23:48 UTC, kirillova-ak5 requested changes

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/allmall.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
this file souldnt be commited, add *.pro.user in your gitignore

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/core/main.cpp
> +    MainWindow w;
we change codestyle?

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/core/viewer.cpp
> +        QPainter p(viewport());
you draw twise, with imagePainter and with p - why?

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/viewer.h
> +#include <QGraphicsView>
includes of big complex classes shoud be in .cpp, in .h use forward declaration

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/viewer.h
> +    qreal zoomFactor();
why qreal instead of standart float and when we change codestyle

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/viewer.h
> +    qreal GetMapPicScale();
why qreal

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/viewer.h
> +    virtual ~viewer() {};
memory leak at mapScene, must delete it here, and delete all objects created in init with "new"

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/mainwindow.h
> +    bool loadFile(const QString &path);
why we have 2 load file whith different names

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/mainwindow.h
> +     //void openFile();
not comment code, delete it

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/mainwindow.h
> +    //void setRenderer(int renderMode);
delete

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/mainwindow.h
> +    void setNewView(QGraphicsSvgItem * toSet);
codestyle

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/mainwindow.h
>  private:
delete this "private" if you already have one before

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/mainwindow.h
> +    QAction *m_nativeAction;
why are you yse m_ prefix

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/mainwindow.cpp
> +    //mapViewer->InitMap(toSet);
dont commit commented code

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/mainwindow.cpp
>          mapInfo->SetAnotherMap(svgFileName, xmlFileName);
may be separate check of svg existing and init from check of xml existing and init

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/svgview.h
> -
should this file be delete?

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/svgview.cpp
> -    black->setElementId(QLatin1String("shop1_1"));
delete this file

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/map.cpp
> +/*
fucking fuck delete commented code

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/map.cpp
> +    QObject(parent), svgMapFileName("")/*, pic(new QGraphicsSvgItem)*/, mapInfoFileName(""), object_indexes()
delete

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/map.cpp
> +        //pic->OpenFile(mapToSet);
delete

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/map.cpp
>      paths = nullptr;
move to initializer list

2021-03-29 23:48 UTC, kirillova-ak5 commented on code/device/map.cpp
> +    pic = new QGraphicsSvgItem(fileName);
where is "delete" for this "new"

2021-03-29 23:48 UTC, kirillova-ak5 commented on graph.cpp
> +#include "device\graph.h"
why are you create file in root of project?

2021-03-29 23:48 UTC, kirillova-ak5 commented on graph.h
> +#ifndef GRAPH_H
why are you create file in root of project?

2021-03-29 23:48 UTC, kirillova-ak5 commented on main.cpp
> +#include <QApplication>
why are you create file in root of project?

2021-03-29 23:48 UTC, kirillova-ak5 commented on mainwindow.cpp
> +#include <QtWidgets>
why are you create file in root of project?

2021-03-29 23:48 UTC, kirillova-ak5 commented on mainwindow.h
> +#ifndef MAINWINDOW_H
why are you create file in root of project?

2021-03-29 23:48 UTC, kirillova-ak5 commented on mainwindow.ui
> +<?xml version="1.0" encoding="UTF-8"?>
why are you create file in root of project?

2021-03-29 23:48 UTC, kirillova-ak5 commented on map.cpp
> +#include <QSvgRenderer>
why are you create file in root of project?

2021-03-29 23:48 UTC, kirillova-ak5 commented on map.h
> +#ifndef MAP_H
why are you create file in root of project? and all next files

2021-03-30 04:44 UTC, merged

2021-04-01 10:22 UTC, HellInsider commented on code/core/main.cpp
> +    MainWindow w;
No, thats ugly first-writed code